# Generated by Django 5.2.6 on 2025-09-09 05:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Namoz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bomdod', models.PositiveIntegerField(default=0)),
                ('peshin', models.PositiveIntegerField(default=0)),
                ('asr', models.PositiveIntegerField(default=0)),
                ('shom', models.PositiveIntegerField(default=0)),
                ('xufton', models.PositiveIntegerField(default=0)),
                ('vitr', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
